---

stages:
  - build
  - test
  - publish

cargo_make:
  stage: build
  tags: 
    - windows
  script:
    - cargo make
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG

cargo_test:
  stage: test
  tags: 
    - windows
  script:
    - cargo make test
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG

cargo_publish:
  stage: publish
  tags: 
    - windows
  script:
    - cargo publish
  rules:
    - if: $CI_COMMIT_TAG

pnpm_build:
  stage: build
  tags: 
    - windows
  script:
    - pnpm install
    - pnpm --filter binding build
    - pnpm --filter core build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/packages/binding/index.js
      - $CI_PROJECT_DIR/packages/binding/index.d.ts
      - $CI_PROJECT_DIR/packages/binding/npm
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG

pnpm_publish:
  stage: publish
  tags: 
    - windows
  script:
    - echo "@npm:registry=https://registry.npmjs.org" > .npmrc
    - echo "//registry.npmjs.org/:_authToken=$Env:NPM_TOKEN" >> .npmrc
    - pnpm --filter binding publish --access public
    - pnpm --filter core publish --access public
  rules:
    - if: $CI_COMMIT_TAG
